// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKaeYOfKim3YuAA2Vy3Q0kEcnavl-vJzk',
    appId: '1:418079729724:web:49db244551e49c37877b39',
    messagingSenderId: '418079729724',
    projectId: 'projectlogin-d6c8d',
    authDomain: 'projectlogin-d6c8d.firebaseapp.com',
    storageBucket: 'projectlogin-d6c8d.appspot.com',
    measurementId: 'G-12KMEJYKP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMqHKI_Kj3w5DGiW1F8ZxYgWYK6OsWYaI',
    appId: '1:418079729724:android:8d32c1c9b57bd88e877b39',
    messagingSenderId: '418079729724',
    projectId: 'projectlogin-d6c8d',
    storageBucket: 'projectlogin-d6c8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoK3N5Jd8f30dImpgPpQrzTCf4-pXYQYY',
    appId: '1:418079729724:ios:8c312a64f2812fe0877b39',
    messagingSenderId: '418079729724',
    projectId: 'projectlogin-d6c8d',
    storageBucket: 'projectlogin-d6c8d.appspot.com',
    iosBundleId: 'com.example.flutterSyahril',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoK3N5Jd8f30dImpgPpQrzTCf4-pXYQYY',
    appId: '1:418079729724:ios:8c312a64f2812fe0877b39',
    messagingSenderId: '418079729724',
    projectId: 'projectlogin-d6c8d',
    storageBucket: 'projectlogin-d6c8d.appspot.com',
    iosBundleId: 'com.example.flutterSyahril',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKaeYOfKim3YuAA2Vy3Q0kEcnavl-vJzk',
    appId: '1:418079729724:web:3540f4bfb07f5d57877b39',
    messagingSenderId: '418079729724',
    projectId: 'projectlogin-d6c8d',
    authDomain: 'projectlogin-d6c8d.firebaseapp.com',
    storageBucket: 'projectlogin-d6c8d.appspot.com',
    measurementId: 'G-25HE4XM8PP',
  );
}
